"""empty message

Revision ID: 45558be076dd
Revises: 8078ea015009
Create Date: 2021-12-12 23:50:40.921294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45558be076dd'
down_revision = '8078ea015009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_hash')
    # ### end Alembic commands ###
