"""empty message

Revision ID: 8078ea015009
Revises: c56ade9da23e
Create Date: 2021-11-22 21:04:18.929044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8078ea015009'
down_revision = 'c56ade9da23e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('location', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'location')
    # ### end Alembic commands ###
