"""empty message

Revision ID: c56ade9da23e
Revises: 4df487940d07
Create Date: 2021-11-21 00:27:45.018948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c56ade9da23e'
down_revision = '4df487940d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('member_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'member_since')
    # ### end Alembic commands ###
